#include "Ten18/PCH.h"
#include "Ten18/Graphics/Vertex.h"

namespace Ten18 { namespace Graphics {
        
const D3D11_INPUT_ELEMENT_DESC Vertex::Layout[] =
{
    { "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT,    0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 },
    { "COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 },
    { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT,       0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 },
};

const UINT Vertex::LayoutCount = ARRAYSIZE(Vertex::Layout);

}}
